name: Make PDF
on: push
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Produce PDF
      run: docker run --rm --volume ${PWD}:/workdir/reports islasgeci/latex make pdf
    - name: Upload
      uses: actions/upload-artifact@main
      with:
        name: paper
        path: paper.pdf
